version: '2'
services:
  # db:
  #   image: postgres:9.5
  #   volumes:
  #     - klaxondb:/var/lib/postgresql/data
  #   networks:
  #     - default
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    entrypoint: /usr/src/app/createdb.sh
    environment:
      DATABASE_URL: "${AQECAHhrXauv6cY0k3VFGkUx9UFWdvCyX3a6yFOMm4QCi5o1gwAAAJowgZcGCSqGSIb3DQEHBqCBiTCBhgIBADCBgAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxWXxaDcjVhr161yB0CARCAU8dbzxK+ru143KUf3U3tSProms4DGC5mh7ZDZYqGCbt2XWRXzA50OG5aORTuf1dfppVw0coUAgDDBAA1kiVhcJOQlr8caE0Ry4/p3ZhnWBLL3Zy/}"
      DATABASE_USERNAME: "${AQECAHhrXauv6cY0k3VFGkUx9UFWdvCyX3a6yFOMm4QCi5o1gwAAAGYwZAYJKoZIhvcNAQcGoFcwVQIBADBQBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDNAnlMPOqssTsJn26wIBEIAjHwJEVoTiYikBVG65+3n4/AVQHJ1QhzS0xBNbMlJM4L+rAAw=}"
      DATABASE_PASSWORD: "${AQECAHhrXauv6cY0k3VFGkUx9UFWdvCyX3a6yFOMm4QCi5o1gwAAAHYwdAYJKoZIhvcNAQcGoGcwZQIBADBgBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDOjKa+U8NudP5lBNHAIBEIAzdwnem9jFDjkZOBumeqf8rt8CLO8UMehLj8RfZdY9fEIgP/2yjGADbA3Vg5/a3VOunze/}"
# volumes:
#   klaxondb:
#     driver: local