volumes:
  postgres_data_local: {}
services:
  db:
    image: postgres:14
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data

  app:
    ports: 
      - "3001:3001"
    env_file:
      - .env.local
    build: .
    depends_on:
      - db