version: '2.2'
volumes:
  postgres_data_local: {}
services:
  db:
    image: postgres:9
    env_file:
      - .env.local
    volumes:
      - postgres_data_local:/var/lib/postgresql/data

  app:
    ports: ["3000:3000"]
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    depends_on:
      - db