version: '2.2'

services:
  database:
    image: "postgres:9.6"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.local

  app:
    links:
    - database
    depends_on:
      database:
        condition: service_healthy
    build: .
    env_file:
      - .env.local
