volumes:
  postgres_data_local: {}
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    volumes:
      - postgres_data_local:/var/lib/postgresql/data

  app:
    ports: 
      - "3001:3001"
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: Dockerfile.server
      # args:
      #   - USE_CRON=true
    depends_on:
      - db
  rake:
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: Dockerfile.rake
    depends_on:
      - db