version: '2'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    entrypoint: /usr/src/app/createdb.sh
    environment:
      DATABASE_URL: "%{AQECAHhrXauv6cY0k3VFGkUx9UFWdvCyX3a6yFOMm4QCi5o1gwAAAM8wgcwGCSqGSIb3DQEHBqCBvjCBuwIBADCBtQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAx7H0nfUYKqum9Z8cACARCAgYeoDI2acpgj9WBYaDlu1fpFlp7Ux2pnxky0idDf/6psLMtrOGixuEx0oZeaDt09ytwsOEprG4xv6n6bqEIkEJV3xPyaEMJXKKzvd//ezttMLZNvTKt7jI50lthTOIoqfbBFhwF5z15dmSlThEmHSvaksYeSTsnLdudAf4z4t9QL6t9/gxSRNwY=}"
    