version: '2.2'
volumes:
  postgres_data_local: {}
services:
  database:
    image: postgres:9
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data

  app:
    ports: 
      - "3000:3000"
    env_file:
      - .env
    # command: bundle exec puma -C config/puma.rb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    depends_on:
      - database