volumes:
  postgres_data_local: {}
services:
  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_DB=klaxon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data

  app:
    ports: 
      - "3000:3000"
    env_file:
      - .env
    # command: bundle exec puma -C config/puma.rb
    build: .
      # context: .
      # dockerfile: Dockerfile
    # volumes:
    #   - .:/code
    depends_on:
      - db