# This generates an ECR repository
# `name` here must  be the same as the `APP_NAME`-rake in the build step

template: v1/cfn/shared/clusters/simple-ecs/service/image.template.yml
stack_name: klaxon-rake-image
region: us-east-1
context:
  name: klaxon-rake
