version: '2.2'

services:
  database:
    image: "postgres:13.3-alpine"
    environment:
      - POSTGRES_USER=klaxon
      - POSTGRES_PASSWORD=secret-psql-password
      - POSTGRES_DB=klaxon
    volumes:
      - ./database:/var/lib/postgresql
  app:
    links:
      - database
    depends_on:
      - database
    image: themarshallproject/klaxon
    env_file: 
      - env_local.list
    ports:
      - change_me:3000
    # Example:
    # - 8885:3000
