default: &default
  adapter: postgresql
  encoding: unicode
  host: klaxondb
  username: postgres
  password:
  port: 5432
  pool: 5

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: postgres
  
production:
  <<: *default
  database: postgres
