default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: root
  password:
  port: 5432
  pool: 5

development:
  <<: *default
  database: klaxon_development

test:
  <<: *default
  database: klaxon_test
  
production:
  <<: *default
  database: klaxon_production
