default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: klaxon_development

test:
  <<: *default
  database: klaxon_test
  
production:
  <<: *default
  database: klaxon_production
  
