# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html
---
AWSTemplateFormatVersion: 2010-09-09

Description: CloudFormation template for an ECS task definition

Parameters:
  Family:
    Type: String
    Default: {{ family }}
  Cpu:
    Type: Number
    Default: 256
  Memory:
    Type: Number
    Default: 512
  NetworkMode:
    Type: String
    Default: bridge
  ExecutionRoleArn:
    Type: String
  # TaskRoleArn:
  #   Type: String
  Image:
    Type: String
    Default: {{ image }}
  ContainerName:
    Type: String
    Default: {{ container_name }}
Resources:
  KlaxonScheduledTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref Family
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      NetworkMode: !Ref NetworkMode
      ExecutionRoleArn: !Ref ExecutionRoleArn
      # TaskRoleArn: !Ref TaskRoleArn
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Ref Image
          
  KlaxonTaskSchedule:
    Type: AWS::Events::Rule
    Properties:
      # Description: String
      # EventBusName: String # optional
      # EventPattern: Json # optional
      # Name: String
      # RoleArn: String
      # ScheduleExpression: String
      # State: String
      # Targets: 
      #   - Target
      Description: Klaxon ecs task scheduler
      Name: klaxon-ecs-task-scheduler
      RoleArn: arn:aws:iam::912288704264:role/ECSTaskExecutionRole
      ScheduleExpression: cron(0/10 * * * ? *)
      State: ENABLED
      Targets:
        - Arn: !Ref KlaxonScheduledTaskDefinition
          Id: klaxon-ecs-task

  # Role that allows EventBridge to schedule an ECS task to run
  # Used for Klaxon
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: A role for event to execute Klaxon ECS task
      RoleName: schedule-ecs-task-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceEventsRole
      # I am unclear on whether I need these policies, going to try first without
      # and uncomment if things don't go my way
      # Policies:
      #   - PolicyName: ScheduleECSTaskPolicy
      #     PolicyDocument:
      #       Statement:
      #         - Effect: Allow
      #           Action:
      #              - iam:PassRole
      #           Resource: "arn:aws:iam::912288704264:role/ECSTaskExecutionRole"
          