_globals:
  # This section is used to accumulate the YAML Anchors for use in the config to DRY the configs
  # This is done to reduce errors due to copying configs from one env/region to another

  - &CLUSTER_PREFIX newsroom
  - &DEBUG false

  # Assuming a config file is named as follows
  # e.g. cfn/config/MyFirstService/dev/us-east-1/config.yml

  # The following two lines extract information from the stackjack config file being executed
  - &FILEPATH "{{ config_file_name }}"
  - !_split &FILENAME [!_split [*FILEPATH, "/", 0, -1], ".", 0, 0]

  # Other information including service name, environment and region are further extracted from the file path
  - !_split &SERVICE_NAME [*FILEPATH, "/", 0, 2]
  - !_split &ENVIRONMENT [*FILEPATH, "/", 0, 3]
  - !_split &REGION [*FILEPATH, "/", 0, 4]

  # Or can be statically defined
  #- &SERVICE_NAME           MyFirstService
  #- &ENVIRONMENT            dev
  #- &REGION                 us-east-1

  # Lastly we assemble the ClusterName and StackName based on data collected above
  #
  - !_join &CLUSTER_NAME ["-", *CLUSTER_PREFIX, *ENVIRONMENT]
  - !_join &STACK_NAME ["-", *CLUSTER_NAME, *SERVICE_NAME]

template: cfn/templates/ecs-task.template.yml
stack_name: *STACK_NAME # newsroom-dev-klaxon-scheduled-task
region: *REGION # us-east-1

context:
  debug: *DEBUG # false
  name: *SERVICE_NAME # klaxon-scheduled-task
  cluster_name: *CLUSTER_NAME # newsroom-dev
  family: klaxon-scheduled-task-dev
  container_name: klaxon-dev
  image: ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/klaxon-rake:dev-latest
  schedule_expression: "0/10 * * * ? *"
  environment:
    DATABASE_URL: "postgresql://{{resolve:secretsmanager:/klaxon/aurora-postgresql-dev/app:SecretString:username}}:{{resolve:secretsmanager:/klaxon/aurora-postgresql-dev/app:SecretString:password}}@{{resolve:secretsmanager:/klaxon/aurora-postgresql-dev/app:SecretString:writer-host}}:5432/klaxon"
    ADMIN_EMAILS: "admin@news.org"
    PORT: 3001
    APP_HOST: klaxon-dev.news-engineering.aws.wapo.pub.
    RACK_ENV: production
    RAILS_ENV: production
    HOST_URL: "sandbox.washpost.arcpublishing.com"
    SECRET_KEY_BASE: "{{resolve:secretsmanager:/klaxon/prod/secret-key:SecretString:secret_key_base}}"
    KLAXON_COMPILE_ASSETS: true
    SMTP_PROVIDER: SES
    SES_ADDRESS: "{{resolve:secretsmanager:/klaxon/ses-prod/smtp-user-credentials:SecretString:address}}"
    SES_DOMAIN: "{{resolve:secretsmanager:/klaxon/ses-prod/smtp-user-credentials:SecretString:domain}}"
    SES_PORT: "{{resolve:secretsmanager:/klaxon/ses-prod/smtp-user-credentials:SecretString:port}}"
    MAILER_FROM_ADDRESS: "{{resolve:secretsmanager:/klaxon/ses-prod/smtp-user-credentials:SecretString:mailerFromAddress}}"
    SES_USERNAME: "{{resolve:secretsmanager:/klaxon/ses-prod/smtp-user-credentials:SecretString:username}}"
    SES_PASSWORD: "{{resolve:secretsmanager:/klaxon/ses-prod/smtp-user-credentials:SecretString:password}}"

    # Datadog env configuration
    DD_ENV: dev
    DD_SERVICE: klaxon-server